# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Yarn CLI
      # You may pin to the exact commit or the version.
      # uses: CultureHQ/actions-yarn@661c6f3a66041c2432bcfb78096b9207304614c8
      uses: CultureHQ/actions-yarn@v1.0.1
    - run: yarn
    - run: yarn lint
    - run: yarn unit-test
    - run: yarn check-deps
    - run: yarn build
